import streamlit as st
import joblib
import pandas as pd
import sys
import os
import ollama

# --------------------------------------------------
# PATHS
# --------------------------------------------------

BASE_DIR = r"C:\Users\paypa\paramedic_ai"
OLLAMA_TOOLS = r"C:\OllamaAI\tools"

MODEL_PATH = os.path.join(BASE_DIR, "model.joblib")
OLLAMA_MODEL = "paramedic-ai:latest"

if OLLAMA_TOOLS not in sys.path:
    sys.path.insert(0, OLLAMA_TOOLS)

try:
    from knowledge_chat import search
    KNOWLEDGE_AVAILABLE = True
except Exception:
    KNOWLEDGE_AVAILABLE = False


# --------------------------------------------------
# LOAD ML MODEL
# --------------------------------------------------

@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)


model = load_model()


# --------------------------------------------------
# PAGE
# --------------------------------------------------

st.set_page_config(
    page_title="Paramedic AI",
    page_icon="🚑",
    layout="wide"
)

st.title("🚑 Paramedic AI")
st.caption("EMS education and decision-support demonstration")


# --------------------------------------------------
# SIDEBAR
# --------------------------------------------------

st.sidebar.header("Patient Assessment")

age = st.sidebar.number_input(
    "Age",
    min_value=0,
    max_value=120,
    value=50
)

heart_rate = st.sidebar.number_input(
    "Heart Rate",
    min_value=0.0,
    max_value=300.0,
    value=90.0
)

systolic_bp = st.sidebar.number_input(
    "Systolic BP",
    min_value=0.0,
    max_value=300.0,
    value=120.0
)

diastolic_bp = st.sidebar.number_input(
    "Diastolic BP",
    min_value=0.0,
    max_value=200.0,
    value=80.0
)

respiratory_rate = st.sidebar.number_input(
    "Respiratory Rate",
    min_value=0.0,
    max_value=100.0,
    value=18.0
)

spo2 = st.sidebar.number_input(
    "SpO₂",
    min_value=0.0,
    max_value=100.0,
    value=98.0
)

temperature = st.sidebar.number_input(
    "Temperature",
    min_value=80.0,
    max_value=115.0,
    value=98.6
)


# --------------------------------------------------
# ML PREDICTION
# --------------------------------------------------

st.header("🧠 ML Risk Assessment")

if st.button("Run ML Assessment", type="primary"):

    patient = pd.DataFrame([{
        "age": age,
        "heart_rate": heart_rate,
        "systolic_bp": systolic_bp,
        "diastolic_bp": diastolic_bp,
        "respiratory_rate": respiratory_rate,
        "spo2": spo2,
        "temperature": temperature
    }])

    try:

        probability = model.predict_proba(patient)[0][1]

        st.metric(
            "Estimated Risk Probability",
            f"{probability * 100:.1f}%"
        )

        if probability >= 0.70:

            st.error("HIGHER RISK")

        elif probability >= 0.40:

            st.warning("INTERMEDIATE RISK")

        else:

            st.success("LOWER RISK")

        st.info(
            "This prediction is generated by the demonstration "
            "machine-learning model and is NOT a clinical diagnosis."
        )

    except Exception as error:

        st.error(f"ML prediction error: {error}")


# --------------------------------------------------
# PARAMEDIC COPILOT
# --------------------------------------------------

st.divider()

st.header("💬 Paramedic Copilot")

if "messages" not in st.session_state:
    st.session_state.messages = []


for message in st.session_state.messages:

    with st.chat_message(message["role"]):
        st.markdown(message["content"])


question = st.chat_input(
    "Ask Paramedic AI a question..."
)


if question:

    st.session_state.messages.append({
        "role": "user",
        "content": question
    })

    with st.chat_message("user"):
        st.markdown(question)

    with st.chat_message("assistant"):

        with st.spinner("Thinking..."):

            try:

                context = ""

                # ------------------------------------------
                # KNOWLEDGE SEARCH
                # ------------------------------------------

                if KNOWLEDGE_AVAILABLE:

                    results = search(question)

                    context_parts = []

                    for number, result in enumerate(
                        results,
                        start=1
                    ):

                        context_parts.append(
                            f"""
SOURCE {number}

Title: {result.get('title', '')}
File: {result.get('source', '')}
Jurisdiction: {result.get('jurisdiction', '')}
Document type: {result.get('document_type', '')}
Effective date: {result.get('effective_date', '')}
Status: {result.get('status', '')}

TEXT:
{result.get('text', '')}
"""
                        )

                    context = "\n".join(context_parts)

                # ------------------------------------------
                # SYSTEM MESSAGE
                # ------------------------------------------

                system_prompt = """
You are Paramedic AI, an EMS education and
decision-support assistant.

Use retrieved reference material when relevant.

Do not invent EMS protocol information.
Do not invent medication doses.
Do not treat training material as current protocol.

For real patient care, current local EMS protocols
and medical direction take precedence.

This application is for education and demonstration.
"""

                if context:

                    system_prompt += f"""

RETRIEVED REFERENCES:

{context}
"""

                messages = [
                    {
                        "role": "system",
                        "content": system_prompt
                    }
                ] + st.session_state.messages

                response = ollama.chat(
                    model=OLLAMA_MODEL,
                    messages=messages
                )

                answer = response["message"]["content"]

                # ------------------------------------------
                # REFERENCES
                # ------------------------------------------

                if KNOWLEDGE_AVAILABLE and results:

                    seen = set()
                    references = []

                    for result in results:

                        source = result.get(
                            "source",
                            "Unknown"
                        )

                        if source not in seen:

                            seen.add(source)

                            references.append(
                                f"- {result.get('title', source)} "
                                f"({result.get('status', '')})"
                            )

                    if references:

                        answer += (
                            "\n\n### References used\n"
                            + "\n".join(references)
                        )

                st.markdown(answer)

                st.session_state.messages.append({
                    "role": "assistant",
                    "content": answer
                })

            except Exception as error:

                error_message = f"Error: {error}"

                st.error(error_message)

                st.session_state.messages.append({
                    "role": "assistant",
                    "content": error_message
                })


# --------------------------------------------------
# SAFETY NOTICE
# --------------------------------------------------

st.divider()

st.caption(
    "DEMO ONLY — NOT FOR CLINICAL DECISION MAKING. "
    "Always follow current local EMS protocols, "
    "medical direction, and applicable regulations."
)
